### ISSUE TITLE
Update syn/quote

### ISSUE THREAD

**Issue by bgermann** [mesalock-linux/enum_to_u8_slice_derive#1]
Hey,

will it be possible to update the macro to build with current syn and quote dependencies? I would like to package this (for MesaLink in Debian) but this is a blocker.

**Comment by dingelish** [comment]
@mssun

**Comment by mssun** [comment]
@bgermann Sure, can you create a PR to fix it. Thanks.

**Comment by bgermann** [comment]
I am not so fluent in Rust macros.

**Comment by dingelish** [comment]
@bgermann let me take a look

**Comment by dingelish** [comment]
@bgermann please check 298cd8a505add184edb3eea2561c3b71f6f4f9ae 

we'll publish if it's ok

**Comment by bgermann** [comment]
Yes. Thanks!
